### ISSUE TITLE
Can I remove remix-app/server.ts?

### ISSUE THREAD

**Issue by Alvazz** [PhilDL/remix-gospel-stack#3]
A core question, what should I do if I don't want to use the remix-app/server.ts method as the backend, but use the api service developed by Golang?

**Comment by PhilDL** [comment]
I don't know if I understood everything clearly but maybe you would like to use Remix as a SPA without server at all? Remix doesn't really do full on "static" mode, you always have some kind of server or deployment target since it is a "Server Framework" and a "Browser Framework". You have an example of deployment target to Vercel in the Turborepo example "kitchen-sink", it has a different `server.ts` file which is not an express server but an adapter for Vercel:

https://github.com/vercel/turbo/tree/main/examples/kitchen-sink/apps/blog

Anyway, whatever the deployment target is (an express server, a lambda function or other) you can call your Golang API  endpoints from the different `loader` and `action`. In that case you don't really need prisma, or the database package since your API If you want more help you should join the Remix discord: https://rmx.as/discord people are very helpful there!

**Comment by Alvazz** [comment]
Yes, I don't need prisma and database package, I just need to call the remote api server (it may be written in Golang or Java), then the api server will return the data, after remix gets the data, display.

Not sure if my assumption is correct, I came across this article:
https://remix.run/docs/en/v1/guides/bff#backend-for-your-frontend

**Comment by Alvazz** [comment]
OK, I have figured it out, even if the database and prisma are excluded, and the data is obtained from the remote api, it is still SSR.
Thank you for making this template, it's very useful!

**Comment by PhilDL** [comment]
Thank you, yes it is still SSR.

I am closing the issue then, have fun with Remix!
